### ISSUE TITLE
Bot doesn't always connect to correct channel , especially when disconnected before.

### ISSUE THREAD

**Issue by baabaablackgoat** [MGF1998/SolsticeBot#83]
time for  `investigation`

**Comment by baabaablackgoat** [comment]
Proooooooobably related to #80
```
TypeError: this.encoder.delete is not a function
    at OpusScriptEngine.destroy (C:\Users\Anwender\Desktop\Main\Git\SolsticeBot\node_modules\discord.js\src\client\voice\opus\OpusScriptEngine.js:37:24)
    at AudioPlayer.destroy (C:\Users\Anwender\Desktop\Main\Git\SolsticeBot\node_modules\discord.js\src\client\voice\player\AudioPlayer.js:69:44)
    at VoiceConnection.disconnect (C:\Users\Anwender\Desktop\Main\Git\SolsticeBot\node_modules\discord.js\src\client\voice\VoiceConnection.js:307:17)
    at nextInQueue (C:\Users\Anwender\Desktop\Main\Git\SolsticeBot\modules\nextinqueue.js:50:41)
    at StreamDispatcher.bot._player.connection.dispatcher.on (C:\Users\Anwender\Desktop\Main\Git\SolsticeBot\modules\nextinqueue.js:35:17)
    at emitOne (events.js:101:20)
    at StreamDispatcher.emit (events.js:191:7)
    at StreamDispatcher.destroy (C:\Users\Anwender\Desktop\Main\Git\SolsticeBot\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:282:10)
    at Socket.stream.on.err (C:\Users\Anwender\Desktop\Main\Git\SolsticeBot\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:302:39)
    at emitNone (events.js:91:20)
```
