### ISSUE TITLE
Dispatcher crash

### ISSUE THREAD

**Issue by baabaablackgoat** [MGF1998/SolsticeBot#9]
```
solstice.js:147
        dispatcher.end();
                  ^

TypeError: Cannot read property 'end' of null
    at flushQueue (D:\Anderes\Discord Bot\solstice.js:147:12)
    at disconnect (D:\Anderes\Discord Bot\solstice.js:231:9)
    at checkQueue (D:\Anderes\Discord Bot\solstice.js:76:13)
    at StreamDispatcher.<anonymous> (D:\Anderes\Discord Bot\solstice.js:102:4)
    at emitOne (events.js:101:20)
    at StreamDispatcher.emit (events.js:188:7)
    at StreamDispatcher._triggerEnd (D:\Anderes\Discord Bot\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:244:10)
    at StreamDispatcher._triggerTerminalState (D:\Anderes\Discord Bot\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:269:14)
    at Socket.stream.on.err (D:\Anderes\Discord Bot\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:286:39)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)

```

**Comment by baabaablackgoat** [comment]
Bug has been fixed in branch feature_roles, will merge with master soon:tm:
